Restructure `extract`.
The new structure is a bit cleaner. Also, 'ar' and 'tar'/'xz' archive
support has been added.

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -1,21 +1,29 @@
 #!/bin/bash
 # Extracts various archives
-if [ -f $1 ] ; then
-	case $1 in
-		*.xz)        tar xJf $1 ;;
-		*.tar.bz2)   tar xjf $1 ;;
-		*.tar.gz)    tar xzf $1 ;;
-		*.bz2)       bunzip2 -- $1 ;;
-		*.rar)       rar x $1   ;;
-		*.gz)        gunzip -- $1  ;;
-		*.tar)       tar xf $1  ;;
-		*.tbz2)      tar xjf $1 ;;
-		*.tgz)       tar xzf $1 ;;
-		*.zip)       unzip -- $1   ;;
-		*.Z)         uncompress -- $1 ;;
-		*.7z)        7z x $1    ;;
-		*)           echo "'$1' cannot be extracted via extract." ;;
-	esac
-else
-	echo "'$1' is not a valid file."
+
+if [[ $# = 0 ]] ; then
+	echo "No file specified."
+	exit 1
 fi
+
+if [[ ! -f "$1" ]] ; then
+    echo "'$1' does not exist."
+    exit 1
+fi
+
+case "$1" in
+    *.tar.bz2)   tar xvjf "$1"   ;;
+    *.tar.xz)    tar xvJf "$1"   ;;
+    *.tar.gz)    tar xvzf "$1"   ;;
+    *.bz2)       bunzip2 "$1"    ;;
+    *.rar)       rar x "$1"      ;;
+    *.gz)        gunzip "$1"     ;;
+    *.tar)       tar xvf "$1"    ;;
+    *.tbz2)      tar xvjf "$1"   ;;
+    *.tgz)       tar xvzf "$1"   ;;
+    *.zip)       unzip "$1"      ;;
+    *.Z)         uncompress "$1" ;;
+    *.7z)        7z x "$1"       ;;
+    *.a)         ar x "$1"       ;;
+    *)           echo "Unable to extract '$1'." ;;
+esac
