needs: Make some mostly semantic changes.

diff --git a/needs b/needs
--- a/needs
+++ b/needs
@@ -7,9 +7,9 @@ die() {
 
 while [ -n "$1" ] ; do
 	case "$1" in
-		-e) extra_error="$2" ;  shift ;;
+		-e) extra_error=$2 ;  shift ;;
 		root) [ $UID -eq 0 ] || die "Must be root. $extra_error" ;;
-		*) command -v "$1" 2>&1 > /dev/null || die "Needs $1. $extra_error" ;;
+		*) command -v "$1" > /dev/null 2>&1 || die "Needs $1. $extra_error" ;;
 	esac
 	shift
 done
