Make sure /etc/sudoers is readable in `sec-check`.

diff --git a/sec-check b/sec-check
--- a/sec-check
+++ b/sec-check
@@ -50,11 +50,15 @@ echo "Cron allow"
 grep -v '^#' cron.allow
 
 echo
-echo "Sudo:"
-grep -Ev '^#|^$' /etc/sudoers
-echo
-echo "Sudo NOPASSWD:"
-grep -v '^#' /etc/sudoers | grep 'NOPASSWD'
+if [[ -r /etc/sudoers ]] ; then
+	echo "Sudo:"
+	grep -Ev '^#|^$' /etc/sudoers
+	echo
+	echo "Sudo NOPASSWD:"
+	grep -v '^#' /etc/sudoers | grep 'NOPASSWD'
+else
+	echo >&2 "Unable to read '/etc/sudoers'"
+fi
 
 if $file_checks ; then
 	# TODO: files without ?00 permissions
